import React from "react";
import {
  FileCode,
  ShieldCheck,
  ExternalLink,
  Sparkles,
  Clock,
  Terminal,
  Copy,
  Check
} from "lucide-react";
import { ReportButton } from "../ReportButton";
import { HardwareComponent, GeneratedScript } from "../../types";

interface CodeGeneratorTabProps {
  activeDrawer: HardwareComponent[];
  activeMCU: HardwareComponent;
  selectedScriptComponent: HardwareComponent;
  setSelectedScriptComponent: (comp: HardwareComponent) => void;
  scriptFormat: "arduino_sketch" | "python_driver" | "bash_install" | "ros_launch";
  setScriptFormat: (format: "arduino_sketch" | "python_driver" | "bash_install" | "ros_launch") => void;
  scriptLoading: boolean;
  generatedScript: GeneratedScript | null;
  onGenerateCode: () => void;
  onCopy: (text: string) => void;
  copiedText: boolean;
}

export const CodeGeneratorTab: React.FC<CodeGeneratorTabProps> = ({
  activeDrawer,
  activeMCU,
  selectedScriptComponent,
  setSelectedScriptComponent,
  scriptFormat,
  setScriptFormat,
  scriptLoading,
  generatedScript,
  onGenerateCode,
  onCopy,
  copiedText
}) => {
  return (
    <div className="bg-slate-900/30 rounded-xl border border-slate-800 p-6 shadow-2xl flex flex-col gap-5">
      <div className="pb-3 border-b border-slate-800/60">
        <h3 className="text-base font-bold text-white flex items-center gap-2 font-mono">
          <FileCode className="w-5 h-5 text-cyan-400" />
          Software Environment Configuration & Code Wizard
        </h3>
        <p className="text-xs text-slate-400">
          Generate drivers, shell installers, launch templates, and sketches specific to your robot inventory.
        </p>
      </div>

      {/* US & NATO Open Source Software Integrity & Privacy Banner */}
      <div className="p-4 bg-emerald-950/20 border border-emerald-900/40 rounded-lg flex flex-col gap-2.5">
        <div className="flex items-center justify-between flex-wrap gap-2">
          <div className="flex items-center gap-2">
            <ShieldCheck className="w-5 h-5 text-emerald-400 shrink-0" />
            <h4 className="text-xs font-bold font-mono text-emerald-300 uppercase tracking-wider">
              US & NATO Open-Source Software Stack & Privacy Commitment
            </h4>
          </div>
          <span className="text-[10px] font-mono bg-emerald-950 text-emerald-400 px-2 py-0.5 rounded border border-emerald-800 shrink-0">
            Zero Telemetry • Zero Spyware
          </span>
        </div>
        <p className="text-xs text-slate-300 leading-relaxed font-sans">
          All software drivers, Python scripts, Arduino libraries, and ROS 2 launch nodes generated by AI RoboPet are built on <strong>100% open-source US and NATO-aligned foundations</strong> (Open Robotics ROS 2 - CA, USA; Linux Foundation - SF, USA; Adafruit Industries - NYC, USA; SparkFun Electronics - CO, USA; Arduino Core - USA/NATO). No proprietary third-party apps or data collection required.
        </p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-2 pt-1 border-t border-emerald-900/30 text-[11px] font-mono text-slate-300">
          <a href="https://github.com/ros2" target="_blank" rel="noopener noreferrer" className="p-2 bg-slate-950/80 rounded border border-slate-800 hover:border-emerald-500/50 hover:text-emerald-300 transition flex items-center justify-between">
            <span>ROS 2 Core (USA)</span>
            <ExternalLink className="w-3 h-3 text-slate-500" />
          </a>
          <a href="https://github.com/adafruit" target="_blank" rel="noopener noreferrer" className="p-2 bg-slate-950/80 rounded border border-slate-800 hover:border-emerald-500/50 hover:text-emerald-300 transition flex items-center justify-between">
            <span>Adafruit Drivers (USA)</span>
            <ExternalLink className="w-3 h-3 text-slate-500" />
          </a>
          <a href="https://github.com/sparkfun" target="_blank" rel="noopener noreferrer" className="p-2 bg-slate-950/80 rounded border border-slate-800 hover:border-emerald-500/50 hover:text-emerald-300 transition flex items-center justify-between">
            <span>SparkFun HAL (USA)</span>
            <ExternalLink className="w-3 h-3 text-slate-500" />
          </a>
          <a href="https://github.com/arduino" target="_blank" rel="noopener noreferrer" className="p-2 bg-slate-950/80 rounded border border-slate-800 hover:border-emerald-500/50 hover:text-emerald-300 transition flex items-center justify-between">
            <span>Arduino Stack (US/NATO)</span>
            <ExternalLink className="w-3 h-3 text-slate-500" />
          </a>
        </div>
      </div>

      {/* Wizard Selector bars */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="flex flex-col gap-1.5">
          <label className="text-xs text-slate-400 font-mono">Select Target Component to drive:</label>
          <select
            value={selectedScriptComponent.id}
            onChange={(e) => {
              const target = activeDrawer.find((c) => c.id === e.target.value);
              if (target) setSelectedScriptComponent(target);
            }}
            className="bg-slate-950 border border-slate-850 text-xs rounded p-3 text-white font-mono focus:outline-none focus:border-cyan-500"
          >
            {activeDrawer
              .filter((c) => c.category !== "Microcontroller" && c.category !== "SBC")
              .map((item) => (
                <option key={item.id} value={item.id}>
                  {item.name} ({item.category})
                </option>
              ))}
          </select>
        </div>

        <div className="flex flex-col gap-1.5">
          <label className="text-xs text-slate-400 font-mono">Select Script/Code Output Format:</label>
          <div className="grid grid-cols-2 gap-1.5">
            {[
              { id: "arduino_sketch", label: "Arduino (.ino)" },
              { id: "python_driver", label: "Python Driver (.py)" },
              { id: "bash_install", label: "Bash Setup (.sh)" },
              { id: "ros_launch", label: "ROS 2 Launch (.py)" }
            ].map((fmt) => (
              <button
                key={fmt.id}
                onClick={() => setScriptFormat(fmt.id as unknown)}
                className={`p-2 rounded border text-[11px] font-mono leading-none transition text-center cursor-pointer ${
                  scriptFormat === fmt.id
                    ? "bg-cyan-950/30 border-cyan-500 text-white"
                    : "bg-slate-950 border-slate-850 text-slate-400 hover:text-white"
                }`}
              >
                {fmt.label}
              </button>
            ))}
          </div>
        </div>
      </div>

      <div className="flex justify-end pt-1">
        <button
          onClick={onGenerateCode}
          disabled={scriptLoading}
          className="w-full sm:w-auto px-5 py-3 bg-cyan-600 hover:bg-cyan-500 text-white font-bold font-mono text-xs rounded hover:shadow-[0_0_15px_rgba(6,182,212,0.3)] border-0 transition-all flex items-center justify-center gap-1.5 cursor-pointer"
        >
          {scriptLoading ? (
            <>
              <Clock className="w-3.5 h-3.5 animate-spin" />
              Weaving Code...
            </>
          ) : (
            <>
              <Sparkles className="w-3.5 h-3.5" />
              Generate Custom {scriptFormat === "arduino_sketch" ? "Arduino Sketch" : scriptFormat === "python_driver" ? "Python Driver" : scriptFormat === "bash_install" ? "Bash Script" : "ROS 2 Launch file"}
            </>
          )}
        </button>
      </div>

      {/* Display generated scripts */}
      {generatedScript && !scriptLoading && (
        <div className="flex flex-col gap-4">
          {/* Title and copy banner */}
          <div className="bg-slate-950 px-4 py-2.5 border border-slate-850 rounded flex items-center justify-between text-xs">
            <span className="font-mono text-cyan-400 flex items-center gap-1.5">
              <Terminal className="w-4 h-4 text-cyan-500" />
              Filename: {generatedScript.scriptTitle}
            </span>
            <div className="flex items-center gap-3">
            <ReportButton
              targetType="ai_output"
              targetId="code-generator"
              excerpt={`${generatedScript.scriptTitle}\n${generatedScript.codeBlock}`}
            />
            <button
              onClick={() => onCopy(generatedScript.codeBlock)}
              className="px-2.5 py-1 bg-slate-900 border border-slate-800 hover:border-cyan-500 text-slate-400 hover:text-white rounded flex items-center gap-1 font-mono text-[11px] transition cursor-pointer"
            >
              {copiedText ? (
                <>
                  <Check className="w-3 h-3 text-emerald-400" />
                  Copied
                </>
              ) : (
                <>
                  <Copy className="w-3 h-3" />
                  Copy Code
                </>
              )}
            </button>
            </div>
          </div>

          {/* Prerequisites */}
          <div className="p-3 bg-slate-950 border border-slate-850 rounded text-xs flex flex-col gap-1">
            <span className="text-[10px] text-slate-500 uppercase tracking-widest font-mono">Workspace Prerequisites:</span>
            <ul className="list-disc pl-4 space-y-0.5 text-slate-350">
              {generatedScript.prerequisites.map((p, i) => (
                <li key={i}>{p}</li>
              ))}
            </ul>
          </div>

          {/* Code Editor view */}
          <div className="relative">
            <pre className="p-4 bg-slate-950 border border-slate-850 rounded overflow-x-auto text-[11px] font-mono text-cyan-400 max-h-[350px] leading-relaxed">
              {generatedScript.codeBlock}
            </pre>
          </div>

          {/* Instructions */}
          <div className="p-4 bg-cyan-950/20 rounded border border-cyan-900/30 text-xs">
            <span className="text-[10px] text-cyan-400 font-mono uppercase tracking-wider block mb-1">Execution / Installation Steps:</span>
            <p className="text-slate-300 leading-relaxed whitespace-pre-line font-mono text-[11px]">{generatedScript.instructions}</p>
          </div>
        </div>
      )}
    </div>
  );
};
